// State de productos
export const OBTENER_PRODUCTOS_EXISTENTE = "OBTENER_PRODUCTOS_EXISTENTE";

// State para el pedidos
export const SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO";
export const CONFIRMAR_PEDIDO_PLATILLO = "CONFIRMAR_PEDIDO_PLATILLO";
export const RESUMEN_PEDIDO = "RESUMEN_PEDIDO";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const PEDIDO_ORDENADO = "PEDIDO_ORDENADO";